import type { Product as SpreeProduct } from '@spree/sdk'

export const baseProduct = {
  id: 'product-1',
  name: 'Everyday Bowl',
  slug: 'everyday-bowl',
  meta_title: null,
  meta_description: null,
  meta_keywords: null,
  variant_count: 1,
  available_on: '2026-01-01',
  preorder_ships_at: null,
  purchasable: true,
  preorder: false,
  in_stock: true,
  backorderable: false,
  available: true,
  description: 'A useful bowl.',
  description_html: '<p>A useful bowl.</p>',
  default_variant_id: 'variant-1',
  thumbnail_url: 'https://example.com/thumb.jpg',
  tags: [],
  price: {
    id: 'price-1',
    amount: '24.00',
    amount_in_cents: 2400,
    compare_at_amount: null,
    compare_at_amount_in_cents: null,
    currency: 'USD',
    display_amount: '$24.00',
    display_compare_at_amount: null,
    price_list_id: null,
  },
  original_price: null,
} satisfies SpreeProduct
