/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as CollectionsSplatRouteImport } from './routes/collections/$'
import { Route as ApiObservabilityRouteImport } from './routes/api/observability'
import { Route as CountryLocaleRouteImport } from './routes/$country/$locale'
import { Route as CountryLocaleIndexRouteImport } from './routes/$country/$locale/index'
import { Route as CountryLocaleCartRouteImport } from './routes/$country/$locale/cart'
import { Route as CountryLocaleProductsIndexRouteImport } from './routes/$country/$locale/products/index'
import { Route as CountryLocaleCheckoutIndexRouteImport } from './routes/$country/$locale/checkout/index'
import { Route as CountryLocaleProductsSlugRouteImport } from './routes/$country/$locale/products/$slug'
import { Route as CountryLocalePoliciesSlugRouteImport } from './routes/$country/$locale/policies/$slug'
import { Route as CountryLocaleOrderPlacedIdRouteImport } from './routes/$country/$locale/order-placed/$id'
import { Route as CountryLocaleNewsletterVerifyRouteImport } from './routes/$country/$locale/newsletter/verify'
import { Route as CountryLocaleConfirmPaymentIdRouteImport } from './routes/$country/$locale/confirm-payment/$id'
import { Route as CountryLocaleCollectionsSplatRouteImport } from './routes/$country/$locale/collections/$'
import { Route as CountryLocaleCheckoutIdRouteImport } from './routes/$country/$locale/checkout/$id'
import { Route as CountryLocaleAccountResetPasswordRouteImport } from './routes/$country/$locale/account/reset-password'
import { Route as CountryLocaleAccountRegisterRouteImport } from './routes/$country/$locale/account/register'
import { Route as CountryLocaleAccountLoginRouteImport } from './routes/$country/$locale/account/login'
import { Route as CountryLocaleAccountForgotPasswordRouteImport } from './routes/$country/$locale/account/forgot-password'
import { Route as CountryLocaleAccountAuthenticatedRouteImport } from './routes/$country/$locale/account/_authenticated'
import { Route as CountryLocaleAccountAuthenticatedIndexRouteImport } from './routes/$country/$locale/account/_authenticated/index'
import { Route as CountryLocaleAccountAuthenticatedProfileRouteImport } from './routes/$country/$locale/account/_authenticated/profile'
import { Route as CountryLocaleAccountAuthenticatedOrdersRouteImport } from './routes/$country/$locale/account/_authenticated/orders'
import { Route as CountryLocaleAccountAuthenticatedGiftCardsRouteImport } from './routes/$country/$locale/account/_authenticated/gift-cards'
import { Route as CountryLocaleAccountAuthenticatedCreditCardsRouteImport } from './routes/$country/$locale/account/_authenticated/credit-cards'
import { Route as CountryLocaleAccountAuthenticatedAddressesRouteImport } from './routes/$country/$locale/account/_authenticated/addresses'
import { Route as CountryLocaleAccountAuthenticatedOrdersIndexRouteImport } from './routes/$country/$locale/account/_authenticated/orders/index'
import { Route as CountryLocaleAccountAuthenticatedOrdersIdRouteImport } from './routes/$country/$locale/account/_authenticated/orders/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSplatRoute = CollectionsSplatRouteImport.update({
  id: '/collections/$',
  path: '/collections/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityRoute = ApiObservabilityRouteImport.update({
  id: '/api/observability',
  path: '/api/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryLocaleRoute = CountryLocaleRouteImport.update({
  id: '/$country/$locale',
  path: '/$country/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryLocaleIndexRoute = CountryLocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryLocaleRoute,
} as any)
const CountryLocaleCartRoute = CountryLocaleCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryLocaleRoute,
} as any)
const CountryLocaleProductsIndexRoute =
  CountryLocaleProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleCheckoutIndexRoute =
  CountryLocaleCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleProductsSlugRoute =
  CountryLocaleProductsSlugRouteImport.update({
    id: '/products/$slug',
    path: '/products/$slug',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocalePoliciesSlugRoute =
  CountryLocalePoliciesSlugRouteImport.update({
    id: '/policies/$slug',
    path: '/policies/$slug',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleOrderPlacedIdRoute =
  CountryLocaleOrderPlacedIdRouteImport.update({
    id: '/order-placed/$id',
    path: '/order-placed/$id',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleNewsletterVerifyRoute =
  CountryLocaleNewsletterVerifyRouteImport.update({
    id: '/newsletter/verify',
    path: '/newsletter/verify',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleConfirmPaymentIdRoute =
  CountryLocaleConfirmPaymentIdRouteImport.update({
    id: '/confirm-payment/$id',
    path: '/confirm-payment/$id',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleCollectionsSplatRoute =
  CountryLocaleCollectionsSplatRouteImport.update({
    id: '/collections/$',
    path: '/collections/$',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleCheckoutIdRoute = CountryLocaleCheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => CountryLocaleRoute,
} as any)
const CountryLocaleAccountResetPasswordRoute =
  CountryLocaleAccountResetPasswordRouteImport.update({
    id: '/account/reset-password',
    path: '/account/reset-password',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleAccountRegisterRoute =
  CountryLocaleAccountRegisterRouteImport.update({
    id: '/account/register',
    path: '/account/register',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleAccountLoginRoute =
  CountryLocaleAccountLoginRouteImport.update({
    id: '/account/login',
    path: '/account/login',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleAccountForgotPasswordRoute =
  CountryLocaleAccountForgotPasswordRouteImport.update({
    id: '/account/forgot-password',
    path: '/account/forgot-password',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleAccountAuthenticatedRoute =
  CountryLocaleAccountAuthenticatedRouteImport.update({
    id: '/account/_authenticated',
    path: '/account',
    getParentRoute: () => CountryLocaleRoute,
  } as any)
const CountryLocaleAccountAuthenticatedIndexRoute =
  CountryLocaleAccountAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CountryLocaleAccountAuthenticatedRoute,
  } as any)
const CountryLocaleAccountAuthenticatedProfileRoute =
  CountryLocaleAccountAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => CountryLocaleAccountAuthenticatedRoute,
  } as any)
const CountryLocaleAccountAuthenticatedOrdersRoute =
  CountryLocaleAccountAuthenticatedOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => CountryLocaleAccountAuthenticatedRoute,
  } as any)
const CountryLocaleAccountAuthenticatedGiftCardsRoute =
  CountryLocaleAccountAuthenticatedGiftCardsRouteImport.update({
    id: '/gift-cards',
    path: '/gift-cards',
    getParentRoute: () => CountryLocaleAccountAuthenticatedRoute,
  } as any)
const CountryLocaleAccountAuthenticatedCreditCardsRoute =
  CountryLocaleAccountAuthenticatedCreditCardsRouteImport.update({
    id: '/credit-cards',
    path: '/credit-cards',
    getParentRoute: () => CountryLocaleAccountAuthenticatedRoute,
  } as any)
const CountryLocaleAccountAuthenticatedAddressesRoute =
  CountryLocaleAccountAuthenticatedAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => CountryLocaleAccountAuthenticatedRoute,
  } as any)
const CountryLocaleAccountAuthenticatedOrdersIndexRoute =
  CountryLocaleAccountAuthenticatedOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CountryLocaleAccountAuthenticatedOrdersRoute,
  } as any)
const CountryLocaleAccountAuthenticatedOrdersIdRoute =
  CountryLocaleAccountAuthenticatedOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => CountryLocaleAccountAuthenticatedOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$country/$locale': typeof CountryLocaleRouteWithChildren
  '/api/observability': typeof ApiObservabilityRoute
  '/collections/$': typeof CollectionsSplatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/$country/$locale/cart': typeof CountryLocaleCartRoute
  '/$country/$locale/': typeof CountryLocaleIndexRoute
  '/$country/$locale/account': typeof CountryLocaleAccountAuthenticatedRouteWithChildren
  '/$country/$locale/account/forgot-password': typeof CountryLocaleAccountForgotPasswordRoute
  '/$country/$locale/account/login': typeof CountryLocaleAccountLoginRoute
  '/$country/$locale/account/register': typeof CountryLocaleAccountRegisterRoute
  '/$country/$locale/account/reset-password': typeof CountryLocaleAccountResetPasswordRoute
  '/$country/$locale/checkout/$id': typeof CountryLocaleCheckoutIdRoute
  '/$country/$locale/collections/$': typeof CountryLocaleCollectionsSplatRoute
  '/$country/$locale/confirm-payment/$id': typeof CountryLocaleConfirmPaymentIdRoute
  '/$country/$locale/newsletter/verify': typeof CountryLocaleNewsletterVerifyRoute
  '/$country/$locale/order-placed/$id': typeof CountryLocaleOrderPlacedIdRoute
  '/$country/$locale/policies/$slug': typeof CountryLocalePoliciesSlugRoute
  '/$country/$locale/products/$slug': typeof CountryLocaleProductsSlugRoute
  '/$country/$locale/checkout/': typeof CountryLocaleCheckoutIndexRoute
  '/$country/$locale/products/': typeof CountryLocaleProductsIndexRoute
  '/$country/$locale/account/addresses': typeof CountryLocaleAccountAuthenticatedAddressesRoute
  '/$country/$locale/account/credit-cards': typeof CountryLocaleAccountAuthenticatedCreditCardsRoute
  '/$country/$locale/account/gift-cards': typeof CountryLocaleAccountAuthenticatedGiftCardsRoute
  '/$country/$locale/account/orders': typeof CountryLocaleAccountAuthenticatedOrdersRouteWithChildren
  '/$country/$locale/account/profile': typeof CountryLocaleAccountAuthenticatedProfileRoute
  '/$country/$locale/account/': typeof CountryLocaleAccountAuthenticatedIndexRoute
  '/$country/$locale/account/orders/$id': typeof CountryLocaleAccountAuthenticatedOrdersIdRoute
  '/$country/$locale/account/orders/': typeof CountryLocaleAccountAuthenticatedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/observability': typeof ApiObservabilityRoute
  '/collections/$': typeof CollectionsSplatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/$country/$locale/cart': typeof CountryLocaleCartRoute
  '/$country/$locale': typeof CountryLocaleIndexRoute
  '/$country/$locale/account/forgot-password': typeof CountryLocaleAccountForgotPasswordRoute
  '/$country/$locale/account/login': typeof CountryLocaleAccountLoginRoute
  '/$country/$locale/account/register': typeof CountryLocaleAccountRegisterRoute
  '/$country/$locale/account/reset-password': typeof CountryLocaleAccountResetPasswordRoute
  '/$country/$locale/checkout/$id': typeof CountryLocaleCheckoutIdRoute
  '/$country/$locale/collections/$': typeof CountryLocaleCollectionsSplatRoute
  '/$country/$locale/confirm-payment/$id': typeof CountryLocaleConfirmPaymentIdRoute
  '/$country/$locale/newsletter/verify': typeof CountryLocaleNewsletterVerifyRoute
  '/$country/$locale/order-placed/$id': typeof CountryLocaleOrderPlacedIdRoute
  '/$country/$locale/policies/$slug': typeof CountryLocalePoliciesSlugRoute
  '/$country/$locale/products/$slug': typeof CountryLocaleProductsSlugRoute
  '/$country/$locale/checkout': typeof CountryLocaleCheckoutIndexRoute
  '/$country/$locale/products': typeof CountryLocaleProductsIndexRoute
  '/$country/$locale/account/addresses': typeof CountryLocaleAccountAuthenticatedAddressesRoute
  '/$country/$locale/account/credit-cards': typeof CountryLocaleAccountAuthenticatedCreditCardsRoute
  '/$country/$locale/account/gift-cards': typeof CountryLocaleAccountAuthenticatedGiftCardsRoute
  '/$country/$locale/account/profile': typeof CountryLocaleAccountAuthenticatedProfileRoute
  '/$country/$locale/account': typeof CountryLocaleAccountAuthenticatedIndexRoute
  '/$country/$locale/account/orders/$id': typeof CountryLocaleAccountAuthenticatedOrdersIdRoute
  '/$country/$locale/account/orders': typeof CountryLocaleAccountAuthenticatedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$country/$locale': typeof CountryLocaleRouteWithChildren
  '/api/observability': typeof ApiObservabilityRoute
  '/collections/$': typeof CollectionsSplatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/$country/$locale/cart': typeof CountryLocaleCartRoute
  '/$country/$locale/': typeof CountryLocaleIndexRoute
  '/$country/$locale/account/_authenticated': typeof CountryLocaleAccountAuthenticatedRouteWithChildren
  '/$country/$locale/account/forgot-password': typeof CountryLocaleAccountForgotPasswordRoute
  '/$country/$locale/account/login': typeof CountryLocaleAccountLoginRoute
  '/$country/$locale/account/register': typeof CountryLocaleAccountRegisterRoute
  '/$country/$locale/account/reset-password': typeof CountryLocaleAccountResetPasswordRoute
  '/$country/$locale/checkout/$id': typeof CountryLocaleCheckoutIdRoute
  '/$country/$locale/collections/$': typeof CountryLocaleCollectionsSplatRoute
  '/$country/$locale/confirm-payment/$id': typeof CountryLocaleConfirmPaymentIdRoute
  '/$country/$locale/newsletter/verify': typeof CountryLocaleNewsletterVerifyRoute
  '/$country/$locale/order-placed/$id': typeof CountryLocaleOrderPlacedIdRoute
  '/$country/$locale/policies/$slug': typeof CountryLocalePoliciesSlugRoute
  '/$country/$locale/products/$slug': typeof CountryLocaleProductsSlugRoute
  '/$country/$locale/checkout/': typeof CountryLocaleCheckoutIndexRoute
  '/$country/$locale/products/': typeof CountryLocaleProductsIndexRoute
  '/$country/$locale/account/_authenticated/addresses': typeof CountryLocaleAccountAuthenticatedAddressesRoute
  '/$country/$locale/account/_authenticated/credit-cards': typeof CountryLocaleAccountAuthenticatedCreditCardsRoute
  '/$country/$locale/account/_authenticated/gift-cards': typeof CountryLocaleAccountAuthenticatedGiftCardsRoute
  '/$country/$locale/account/_authenticated/orders': typeof CountryLocaleAccountAuthenticatedOrdersRouteWithChildren
  '/$country/$locale/account/_authenticated/profile': typeof CountryLocaleAccountAuthenticatedProfileRoute
  '/$country/$locale/account/_authenticated/': typeof CountryLocaleAccountAuthenticatedIndexRoute
  '/$country/$locale/account/_authenticated/orders/$id': typeof CountryLocaleAccountAuthenticatedOrdersIdRoute
  '/$country/$locale/account/_authenticated/orders/': typeof CountryLocaleAccountAuthenticatedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$country/$locale'
    | '/api/observability'
    | '/collections/$'
    | '/products/$slug'
    | '/account/'
    | '/checkout/'
    | '/products/'
    | '/$country/$locale/cart'
    | '/$country/$locale/'
    | '/$country/$locale/account'
    | '/$country/$locale/account/forgot-password'
    | '/$country/$locale/account/login'
    | '/$country/$locale/account/register'
    | '/$country/$locale/account/reset-password'
    | '/$country/$locale/checkout/$id'
    | '/$country/$locale/collections/$'
    | '/$country/$locale/confirm-payment/$id'
    | '/$country/$locale/newsletter/verify'
    | '/$country/$locale/order-placed/$id'
    | '/$country/$locale/policies/$slug'
    | '/$country/$locale/products/$slug'
    | '/$country/$locale/checkout/'
    | '/$country/$locale/products/'
    | '/$country/$locale/account/addresses'
    | '/$country/$locale/account/credit-cards'
    | '/$country/$locale/account/gift-cards'
    | '/$country/$locale/account/orders'
    | '/$country/$locale/account/profile'
    | '/$country/$locale/account/'
    | '/$country/$locale/account/orders/$id'
    | '/$country/$locale/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/observability'
    | '/collections/$'
    | '/products/$slug'
    | '/account'
    | '/checkout'
    | '/products'
    | '/$country/$locale/cart'
    | '/$country/$locale'
    | '/$country/$locale/account/forgot-password'
    | '/$country/$locale/account/login'
    | '/$country/$locale/account/register'
    | '/$country/$locale/account/reset-password'
    | '/$country/$locale/checkout/$id'
    | '/$country/$locale/collections/$'
    | '/$country/$locale/confirm-payment/$id'
    | '/$country/$locale/newsletter/verify'
    | '/$country/$locale/order-placed/$id'
    | '/$country/$locale/policies/$slug'
    | '/$country/$locale/products/$slug'
    | '/$country/$locale/checkout'
    | '/$country/$locale/products'
    | '/$country/$locale/account/addresses'
    | '/$country/$locale/account/credit-cards'
    | '/$country/$locale/account/gift-cards'
    | '/$country/$locale/account/profile'
    | '/$country/$locale/account'
    | '/$country/$locale/account/orders/$id'
    | '/$country/$locale/account/orders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$country/$locale'
    | '/api/observability'
    | '/collections/$'
    | '/products/$slug'
    | '/account/'
    | '/checkout/'
    | '/products/'
    | '/$country/$locale/cart'
    | '/$country/$locale/'
    | '/$country/$locale/account/_authenticated'
    | '/$country/$locale/account/forgot-password'
    | '/$country/$locale/account/login'
    | '/$country/$locale/account/register'
    | '/$country/$locale/account/reset-password'
    | '/$country/$locale/checkout/$id'
    | '/$country/$locale/collections/$'
    | '/$country/$locale/confirm-payment/$id'
    | '/$country/$locale/newsletter/verify'
    | '/$country/$locale/order-placed/$id'
    | '/$country/$locale/policies/$slug'
    | '/$country/$locale/products/$slug'
    | '/$country/$locale/checkout/'
    | '/$country/$locale/products/'
    | '/$country/$locale/account/_authenticated/addresses'
    | '/$country/$locale/account/_authenticated/credit-cards'
    | '/$country/$locale/account/_authenticated/gift-cards'
    | '/$country/$locale/account/_authenticated/orders'
    | '/$country/$locale/account/_authenticated/profile'
    | '/$country/$locale/account/_authenticated/'
    | '/$country/$locale/account/_authenticated/orders/$id'
    | '/$country/$locale/account/_authenticated/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CountryLocaleRoute: typeof CountryLocaleRouteWithChildren
  ApiObservabilityRoute: typeof ApiObservabilityRoute
  CollectionsSplatRoute: typeof CollectionsSplatRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$': {
      id: '/collections/$'
      path: '/collections/$'
      fullPath: '/collections/$'
      preLoaderRoute: typeof CollectionsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability': {
      id: '/api/observability'
      path: '/api/observability'
      fullPath: '/api/observability'
      preLoaderRoute: typeof ApiObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$locale': {
      id: '/$country/$locale'
      path: '/$country/$locale'
      fullPath: '/$country/$locale'
      preLoaderRoute: typeof CountryLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$locale/': {
      id: '/$country/$locale/'
      path: '/'
      fullPath: '/$country/$locale/'
      preLoaderRoute: typeof CountryLocaleIndexRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/cart': {
      id: '/$country/$locale/cart'
      path: '/cart'
      fullPath: '/$country/$locale/cart'
      preLoaderRoute: typeof CountryLocaleCartRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/products/': {
      id: '/$country/$locale/products/'
      path: '/products'
      fullPath: '/$country/$locale/products/'
      preLoaderRoute: typeof CountryLocaleProductsIndexRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/checkout/': {
      id: '/$country/$locale/checkout/'
      path: '/checkout'
      fullPath: '/$country/$locale/checkout/'
      preLoaderRoute: typeof CountryLocaleCheckoutIndexRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/products/$slug': {
      id: '/$country/$locale/products/$slug'
      path: '/products/$slug'
      fullPath: '/$country/$locale/products/$slug'
      preLoaderRoute: typeof CountryLocaleProductsSlugRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/policies/$slug': {
      id: '/$country/$locale/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/$country/$locale/policies/$slug'
      preLoaderRoute: typeof CountryLocalePoliciesSlugRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/order-placed/$id': {
      id: '/$country/$locale/order-placed/$id'
      path: '/order-placed/$id'
      fullPath: '/$country/$locale/order-placed/$id'
      preLoaderRoute: typeof CountryLocaleOrderPlacedIdRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/newsletter/verify': {
      id: '/$country/$locale/newsletter/verify'
      path: '/newsletter/verify'
      fullPath: '/$country/$locale/newsletter/verify'
      preLoaderRoute: typeof CountryLocaleNewsletterVerifyRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/confirm-payment/$id': {
      id: '/$country/$locale/confirm-payment/$id'
      path: '/confirm-payment/$id'
      fullPath: '/$country/$locale/confirm-payment/$id'
      preLoaderRoute: typeof CountryLocaleConfirmPaymentIdRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/collections/$': {
      id: '/$country/$locale/collections/$'
      path: '/collections/$'
      fullPath: '/$country/$locale/collections/$'
      preLoaderRoute: typeof CountryLocaleCollectionsSplatRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/checkout/$id': {
      id: '/$country/$locale/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/$country/$locale/checkout/$id'
      preLoaderRoute: typeof CountryLocaleCheckoutIdRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/account/reset-password': {
      id: '/$country/$locale/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/$country/$locale/account/reset-password'
      preLoaderRoute: typeof CountryLocaleAccountResetPasswordRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/account/register': {
      id: '/$country/$locale/account/register'
      path: '/account/register'
      fullPath: '/$country/$locale/account/register'
      preLoaderRoute: typeof CountryLocaleAccountRegisterRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/account/login': {
      id: '/$country/$locale/account/login'
      path: '/account/login'
      fullPath: '/$country/$locale/account/login'
      preLoaderRoute: typeof CountryLocaleAccountLoginRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/account/forgot-password': {
      id: '/$country/$locale/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/$country/$locale/account/forgot-password'
      preLoaderRoute: typeof CountryLocaleAccountForgotPasswordRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/account/_authenticated': {
      id: '/$country/$locale/account/_authenticated'
      path: '/account'
      fullPath: '/$country/$locale/account'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedRouteImport
      parentRoute: typeof CountryLocaleRoute
    }
    '/$country/$locale/account/_authenticated/': {
      id: '/$country/$locale/account/_authenticated/'
      path: '/'
      fullPath: '/$country/$locale/account/'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedIndexRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedRoute
    }
    '/$country/$locale/account/_authenticated/profile': {
      id: '/$country/$locale/account/_authenticated/profile'
      path: '/profile'
      fullPath: '/$country/$locale/account/profile'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedProfileRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedRoute
    }
    '/$country/$locale/account/_authenticated/orders': {
      id: '/$country/$locale/account/_authenticated/orders'
      path: '/orders'
      fullPath: '/$country/$locale/account/orders'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedOrdersRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedRoute
    }
    '/$country/$locale/account/_authenticated/gift-cards': {
      id: '/$country/$locale/account/_authenticated/gift-cards'
      path: '/gift-cards'
      fullPath: '/$country/$locale/account/gift-cards'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedGiftCardsRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedRoute
    }
    '/$country/$locale/account/_authenticated/credit-cards': {
      id: '/$country/$locale/account/_authenticated/credit-cards'
      path: '/credit-cards'
      fullPath: '/$country/$locale/account/credit-cards'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedCreditCardsRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedRoute
    }
    '/$country/$locale/account/_authenticated/addresses': {
      id: '/$country/$locale/account/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/$country/$locale/account/addresses'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedAddressesRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedRoute
    }
    '/$country/$locale/account/_authenticated/orders/': {
      id: '/$country/$locale/account/_authenticated/orders/'
      path: '/'
      fullPath: '/$country/$locale/account/orders/'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedOrdersIndexRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedOrdersRoute
    }
    '/$country/$locale/account/_authenticated/orders/$id': {
      id: '/$country/$locale/account/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/$country/$locale/account/orders/$id'
      preLoaderRoute: typeof CountryLocaleAccountAuthenticatedOrdersIdRouteImport
      parentRoute: typeof CountryLocaleAccountAuthenticatedOrdersRoute
    }
  }
}

interface CountryLocaleAccountAuthenticatedOrdersRouteChildren {
  CountryLocaleAccountAuthenticatedOrdersIdRoute: typeof CountryLocaleAccountAuthenticatedOrdersIdRoute
  CountryLocaleAccountAuthenticatedOrdersIndexRoute: typeof CountryLocaleAccountAuthenticatedOrdersIndexRoute
}

const CountryLocaleAccountAuthenticatedOrdersRouteChildren: CountryLocaleAccountAuthenticatedOrdersRouteChildren =
  {
    CountryLocaleAccountAuthenticatedOrdersIdRoute:
      CountryLocaleAccountAuthenticatedOrdersIdRoute,
    CountryLocaleAccountAuthenticatedOrdersIndexRoute:
      CountryLocaleAccountAuthenticatedOrdersIndexRoute,
  }

const CountryLocaleAccountAuthenticatedOrdersRouteWithChildren =
  CountryLocaleAccountAuthenticatedOrdersRoute._addFileChildren(
    CountryLocaleAccountAuthenticatedOrdersRouteChildren,
  )

interface CountryLocaleAccountAuthenticatedRouteChildren {
  CountryLocaleAccountAuthenticatedAddressesRoute: typeof CountryLocaleAccountAuthenticatedAddressesRoute
  CountryLocaleAccountAuthenticatedCreditCardsRoute: typeof CountryLocaleAccountAuthenticatedCreditCardsRoute
  CountryLocaleAccountAuthenticatedGiftCardsRoute: typeof CountryLocaleAccountAuthenticatedGiftCardsRoute
  CountryLocaleAccountAuthenticatedOrdersRoute: typeof CountryLocaleAccountAuthenticatedOrdersRouteWithChildren
  CountryLocaleAccountAuthenticatedProfileRoute: typeof CountryLocaleAccountAuthenticatedProfileRoute
  CountryLocaleAccountAuthenticatedIndexRoute: typeof CountryLocaleAccountAuthenticatedIndexRoute
}

const CountryLocaleAccountAuthenticatedRouteChildren: CountryLocaleAccountAuthenticatedRouteChildren =
  {
    CountryLocaleAccountAuthenticatedAddressesRoute:
      CountryLocaleAccountAuthenticatedAddressesRoute,
    CountryLocaleAccountAuthenticatedCreditCardsRoute:
      CountryLocaleAccountAuthenticatedCreditCardsRoute,
    CountryLocaleAccountAuthenticatedGiftCardsRoute:
      CountryLocaleAccountAuthenticatedGiftCardsRoute,
    CountryLocaleAccountAuthenticatedOrdersRoute:
      CountryLocaleAccountAuthenticatedOrdersRouteWithChildren,
    CountryLocaleAccountAuthenticatedProfileRoute:
      CountryLocaleAccountAuthenticatedProfileRoute,
    CountryLocaleAccountAuthenticatedIndexRoute:
      CountryLocaleAccountAuthenticatedIndexRoute,
  }

const CountryLocaleAccountAuthenticatedRouteWithChildren =
  CountryLocaleAccountAuthenticatedRoute._addFileChildren(
    CountryLocaleAccountAuthenticatedRouteChildren,
  )

interface CountryLocaleRouteChildren {
  CountryLocaleCartRoute: typeof CountryLocaleCartRoute
  CountryLocaleIndexRoute: typeof CountryLocaleIndexRoute
  CountryLocaleAccountAuthenticatedRoute: typeof CountryLocaleAccountAuthenticatedRouteWithChildren
  CountryLocaleAccountForgotPasswordRoute: typeof CountryLocaleAccountForgotPasswordRoute
  CountryLocaleAccountLoginRoute: typeof CountryLocaleAccountLoginRoute
  CountryLocaleAccountRegisterRoute: typeof CountryLocaleAccountRegisterRoute
  CountryLocaleAccountResetPasswordRoute: typeof CountryLocaleAccountResetPasswordRoute
  CountryLocaleCheckoutIdRoute: typeof CountryLocaleCheckoutIdRoute
  CountryLocaleCollectionsSplatRoute: typeof CountryLocaleCollectionsSplatRoute
  CountryLocaleConfirmPaymentIdRoute: typeof CountryLocaleConfirmPaymentIdRoute
  CountryLocaleNewsletterVerifyRoute: typeof CountryLocaleNewsletterVerifyRoute
  CountryLocaleOrderPlacedIdRoute: typeof CountryLocaleOrderPlacedIdRoute
  CountryLocalePoliciesSlugRoute: typeof CountryLocalePoliciesSlugRoute
  CountryLocaleProductsSlugRoute: typeof CountryLocaleProductsSlugRoute
  CountryLocaleCheckoutIndexRoute: typeof CountryLocaleCheckoutIndexRoute
  CountryLocaleProductsIndexRoute: typeof CountryLocaleProductsIndexRoute
}

const CountryLocaleRouteChildren: CountryLocaleRouteChildren = {
  CountryLocaleCartRoute: CountryLocaleCartRoute,
  CountryLocaleIndexRoute: CountryLocaleIndexRoute,
  CountryLocaleAccountAuthenticatedRoute:
    CountryLocaleAccountAuthenticatedRouteWithChildren,
  CountryLocaleAccountForgotPasswordRoute:
    CountryLocaleAccountForgotPasswordRoute,
  CountryLocaleAccountLoginRoute: CountryLocaleAccountLoginRoute,
  CountryLocaleAccountRegisterRoute: CountryLocaleAccountRegisterRoute,
  CountryLocaleAccountResetPasswordRoute:
    CountryLocaleAccountResetPasswordRoute,
  CountryLocaleCheckoutIdRoute: CountryLocaleCheckoutIdRoute,
  CountryLocaleCollectionsSplatRoute: CountryLocaleCollectionsSplatRoute,
  CountryLocaleConfirmPaymentIdRoute: CountryLocaleConfirmPaymentIdRoute,
  CountryLocaleNewsletterVerifyRoute: CountryLocaleNewsletterVerifyRoute,
  CountryLocaleOrderPlacedIdRoute: CountryLocaleOrderPlacedIdRoute,
  CountryLocalePoliciesSlugRoute: CountryLocalePoliciesSlugRoute,
  CountryLocaleProductsSlugRoute: CountryLocaleProductsSlugRoute,
  CountryLocaleCheckoutIndexRoute: CountryLocaleCheckoutIndexRoute,
  CountryLocaleProductsIndexRoute: CountryLocaleProductsIndexRoute,
}

const CountryLocaleRouteWithChildren = CountryLocaleRoute._addFileChildren(
  CountryLocaleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CountryLocaleRoute: CountryLocaleRouteWithChildren,
  ApiObservabilityRoute: ApiObservabilityRoute,
  CollectionsSplatRoute: CollectionsSplatRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
